// Code generated by "stringer -type=nodetype -linecomment -output gen_nodetype_stringer.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeKeyword-0]
	_ = x[NodeTypeStatement-1]
	_ = x[NodeTypeString-2]
	_ = x[NodeTypeType-3]
	_ = x[NodeTypeConditional-4]
	_ = x[NodeTypeFunction-5]
	_ = x[NodeTypeComment-6]
	_ = x[NodeTypeLabel-7]
	_ = x[NodeTypeRepeat-8]
}

const _nodetype_name = "KeywordStatementStringTypeConditionalFunctionCommentLabelRepeat"

var _nodetype_index = [...]uint8{0, 7, 16, 22, 26, 37, 45, 52, 57, 63}

func (i nodetype) String() string {
	if i >= nodetype(len(_nodetype_index)-1) {
		return "nodetype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodetype_name[_nodetype_index[i]:_nodetype_index[i+1]]
}
