// Code generated by "stringer -type=nodetype -linecomment -output gen_nodetype_stringer.go"; DO NOT EDIT.

package main

import "strconv"

const _nodetype_name = "KeywordStatementStringTypeConditionalFunctionCommentLabelRepeat"

var _nodetype_index = [...]uint8{0, 7, 16, 22, 26, 37, 45, 52, 57, 63}

func (i nodetype) String() string {
	if i >= nodetype(len(_nodetype_index)-1) {
		return "nodetype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodetype_name[_nodetype_index[i]:_nodetype_index[i+1]]
}
