language: generic
sudo: required

os:
  - linux

env:
  global:
    - GO111MODULE=on
  matrix:
    - GO_VERSION=go1.12.1 VIM_VERSION=v8.1.1103

# Add this before_install until we have a definitive resolution on
# https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/2
before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

before_install:
  - docker --version
  - docker pull myitcv/govim:${GO_VERSION}_${VIM_VERSION} | tee
  - cat Dockerfile.user | envsubst '$GO_VERSION,$VIM_VERSION' | docker build -t govim --build-arg USER=$USER --build-arg UID=$UID --build-arg GID=$(id -g $USER) -

script:
  - ./_scripts/runDockerRun.sh
