// Code generated by "stringer -type=Complete -linecomment -output gen_complete_stringer.go"; DO NOT EDIT.

package govim

import "strconv"

const _Complete_name = "-complete=arglist-complete=augroup-complete=buffer-complete=behave-complete=color-complete=command-complete=compiler-complete=cscope-complete=dir-complete=environment-complete=event-complete=expression-complete=file-complete=file_in_path-complete=filetype-complete=function-complete=help-complete=highlight-complete=history-complete=locale-complete=mapclear-complete=mapping-complete=menu-complete=messages-complete=option-complete=packadd-complete=shellcmd-complete=sign-complete=syntax-complete=syntime-complete=tag-complete=tag_listfiles-complete=user-complete=var"

var _Complete_index = [...]uint16{0, 17, 34, 50, 66, 81, 98, 116, 132, 145, 166, 181, 201, 215, 237, 255, 273, 287, 306, 323, 339, 357, 374, 388, 406, 422, 439, 457, 471, 487, 504, 517, 540, 554, 567}

func (i Complete) String() string {
	if i >= Complete(len(_Complete_index)-1) {
		return "Complete(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Complete_name[_Complete_index[i]:_Complete_index[i+1]]
}
