// Code generated by "stringer -type=Event -linecomment -output gen_event_stringer.go"; DO NOT EDIT.

package govim

import "strconv"

const _Event_name = "BufNewFileBufReadPreBufReadBufReadPostBufReadCmdFileReadPreFileReadPostFileReadCmdFilterReadPreFilterReadPostStdinReadPreStdinReadPostBufWriteBufWritePreBufWritePostBufWriteCmdFileWritePreFileWritePostFileWriteCmdFileAppendPreFileAppendPostFileAppendCmdFilterWritePreFilterWritePostBufAddBufCreateBufDeleteBufWipeoutTerminalOpenBufFilePreBufFilePostBufEnterBufLeaveBufWinEnterBufWinLeaveBufUnloadBufHiddenBufNewSwapExistsFileTypeSyntaxEncodingChangedTermChangedOptionSetVimEnterGUIEnterGUIFailedTermResponseQuitPreExitPreVimLeavePreVimLeaveFileChangedShellFileChangedShellPostFileChangedRODiffUpdatedDirChangedShellCmdPostShellFilterPostCmdUndefinedFuncUndefinedSpellFileMissingSourcePreSourcePostSourceCmdVimResizedFocusGainedFocusLostCursorHoldCursorHoldICursorMovedCursorMovedIWinNewTabNewTabClosedWinEnterWinLeaveTabEnterTabLeaveCmdwinEnterCmdwinLeaveCmdlineChangedCmdlineEnterCmdlineLeaveInsertEnterInsertChangeInsertLeaveInsertCharPreTextChangedTextChangedITextChangedPTextYankPostColorSchemePreColorSchemeRemoteReplyQuickFixCmdPreQuickFixCmdPostSessionLoadPostMenuPopupCompleteDone"

var _Event_index = [...]uint16{0, 10, 20, 27, 38, 48, 59, 71, 82, 95, 109, 121, 134, 142, 153, 165, 176, 188, 201, 213, 226, 240, 253, 267, 282, 288, 297, 306, 316, 328, 338, 349, 357, 365, 376, 387, 396, 405, 411, 421, 429, 435, 450, 461, 470, 478, 486, 495, 507, 514, 521, 532, 540, 556, 576, 589, 600, 610, 622, 637, 649, 662, 678, 687, 697, 706, 716, 727, 736, 746, 757, 768, 780, 786, 792, 801, 809, 817, 825, 833, 844, 855, 869, 881, 893, 904, 916, 927, 940, 951, 963, 975, 987, 1001, 1012, 1023, 1037, 1052, 1067, 1076, 1088}

func (i Event) String() string {
	if i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
