// Code generated by "stringer -type=Range -linecomment -output gen_range_stringer.go"; DO NOT EDIT.

package govim

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RangeLine-0]
	_ = x[RangeFile-1]
}

const _Range_name = "-range-range=%"

var _Range_index = [...]uint8{0, 6, 14}

func (i Range) String() string {
	if i >= Range(len(_Range_index)-1) {
		return "Range(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Range_name[_Range_index[i]:_Range_index[i+1]]
}
