// Code generated by "stringer -type=NArgs -linecomment -output gen_nargs_stringer.go"; DO NOT EDIT.

package govim

import "strconv"

const _NArgs_name = "-nargs=0-nargs=1-nargs=*-nargs=?-nargs=+"

var _NArgs_index = [...]uint8{0, 8, 16, 24, 32, 40}

func (i NArgs) String() string {
	if i >= NArgs(len(_NArgs_index)-1) {
		return "NArgs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NArgs_name[_NArgs_index[i]:_NArgs_index[i+1]]
}
