// Code generated by "stringer -type=GenAttr,Complete,Range,Event,NArgs,Flavor -linecomment -output gen_stringers_stringer.go"; DO NOT EDIT.

package govim

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrBang-0]
	_ = x[AttrBar-1]
	_ = x[AttrRegister-2]
	_ = x[AttrBuffer-3]
}

const _GenAttr_name = "-bang-bar-register-buffer"

var _GenAttr_index = [...]uint8{0, 5, 9, 18, 25}

func (i GenAttr) String() string {
	if i >= GenAttr(len(_GenAttr_index)-1) {
		return "GenAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenAttr_name[_GenAttr_index[i]:_GenAttr_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompleteArglist-0]
	_ = x[CompleteAugroup-1]
	_ = x[CompleteBuffer-2]
	_ = x[CompleteBehave-3]
	_ = x[CompleteColor-4]
	_ = x[CompleteCommand-5]
	_ = x[CompleteCompiler-6]
	_ = x[CompleteCscope-7]
	_ = x[CompleteDir-8]
	_ = x[CompleteEnvironment-9]
	_ = x[CompleteEvent-10]
	_ = x[CompleteExpression-11]
	_ = x[CompleteFile-12]
	_ = x[CompleteFileInPath-13]
	_ = x[CompleteFiletype-14]
	_ = x[CompleteFunction-15]
	_ = x[CompleteHelp-16]
	_ = x[CompleteHighlight-17]
	_ = x[CompleteHistory-18]
	_ = x[CompleteLocale-19]
	_ = x[CompleteMapclear-20]
	_ = x[CompleteMapping-21]
	_ = x[CompleteMenu-22]
	_ = x[CompleteMessages-23]
	_ = x[CompleteOption-24]
	_ = x[CompletePackadd-25]
	_ = x[CompleteShellCmd-26]
	_ = x[CompleteSign-27]
	_ = x[CompleteSyntax-28]
	_ = x[CompleteSyntime-29]
	_ = x[CompleteTag-30]
	_ = x[CompleteTagListFiles-31]
	_ = x[CompleteUser-32]
	_ = x[CompleteVar-33]
}

const _Complete_name = "-complete=arglist-complete=augroup-complete=buffer-complete=behave-complete=color-complete=command-complete=compiler-complete=cscope-complete=dir-complete=environment-complete=event-complete=expression-complete=file-complete=file_in_path-complete=filetype-complete=function-complete=help-complete=highlight-complete=history-complete=locale-complete=mapclear-complete=mapping-complete=menu-complete=messages-complete=option-complete=packadd-complete=shellcmd-complete=sign-complete=syntax-complete=syntime-complete=tag-complete=tag_listfiles-complete=user-complete=var"

var _Complete_index = [...]uint16{0, 17, 34, 50, 66, 81, 98, 116, 132, 145, 166, 181, 201, 215, 237, 255, 273, 287, 306, 323, 339, 357, 374, 388, 406, 422, 439, 457, 471, 487, 504, 517, 540, 554, 567}

func (i Complete) String() string {
	if i >= Complete(len(_Complete_index)-1) {
		return "Complete(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Complete_name[_Complete_index[i]:_Complete_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RangeLine-0]
	_ = x[RangeFile-1]
}

const _Range_name = "-range-range=%"

var _Range_index = [...]uint8{0, 6, 14}

func (i Range) String() string {
	if i >= Range(len(_Range_index)-1) {
		return "Range(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Range_name[_Range_index[i]:_Range_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventBufNewFile-0]
	_ = x[EventBufReadPre-1]
	_ = x[EventBufRead-2]
	_ = x[EventBufReadPost-3]
	_ = x[EventBufReadCmd-4]
	_ = x[EventFileReadPre-5]
	_ = x[EventFileReadPost-6]
	_ = x[EventFileReadCmd-7]
	_ = x[EventFilterReadPre-8]
	_ = x[EventFilterReadPost-9]
	_ = x[EventStdinReadPre-10]
	_ = x[EventStdinReadPost-11]
	_ = x[EventBufWrite-12]
	_ = x[EventBufWritePre-13]
	_ = x[EventBufWritePost-14]
	_ = x[EventBufWriteCmd-15]
	_ = x[EventFileWritePre-16]
	_ = x[EventFileWritePost-17]
	_ = x[EventFileWriteCmd-18]
	_ = x[EventFileAppendPre-19]
	_ = x[EventFileAppendPost-20]
	_ = x[EventFileAppendCmd-21]
	_ = x[EventFilterWritePre-22]
	_ = x[EventFilterWritePost-23]
	_ = x[EventBufAdd-24]
	_ = x[EventBufCreate-25]
	_ = x[EventBufDelete-26]
	_ = x[EventBufWipeout-27]
	_ = x[EventTerminalOpen-28]
	_ = x[EventBufFilePre-29]
	_ = x[EventBufFilePost-30]
	_ = x[EventBufEnter-31]
	_ = x[EventBufLeave-32]
	_ = x[EventBufWinEnter-33]
	_ = x[EventBufWinLeave-34]
	_ = x[EventBufUnload-35]
	_ = x[EventBufHidden-36]
	_ = x[EventBufNew-37]
	_ = x[EventSwapExists-38]
	_ = x[EventFileType-39]
	_ = x[EventSyntax-40]
	_ = x[EventEncodingChanged-41]
	_ = x[EventTermChanged-42]
	_ = x[EventOptionSet-43]
	_ = x[EventVimEnter-44]
	_ = x[EventGUIEnter-45]
	_ = x[EventGUIFailed-46]
	_ = x[EventTermResponse-47]
	_ = x[EventQuitPre-48]
	_ = x[EventExitPre-49]
	_ = x[EventVimLeavePre-50]
	_ = x[EventVimLeave-51]
	_ = x[EventFileChangedShell-52]
	_ = x[EventFileChangedShellPost-53]
	_ = x[EventFileChangedRO-54]
	_ = x[EventDiffUpdated-55]
	_ = x[EventDirChanged-56]
	_ = x[EventShellCmdPost-57]
	_ = x[EventShellFilterPost-58]
	_ = x[EventCmdUndefined-59]
	_ = x[EventFuncUndefined-60]
	_ = x[EventSpellFileMissing-61]
	_ = x[EventSourcePre-62]
	_ = x[EventSourcePost-63]
	_ = x[EventSourceCmd-64]
	_ = x[EventVimResized-65]
	_ = x[EventFocusGained-66]
	_ = x[EventFocusLost-67]
	_ = x[EventCursorHold-68]
	_ = x[EventCursorHoldI-69]
	_ = x[EventCursorMoved-70]
	_ = x[EventCursorMovedI-71]
	_ = x[EventWinNew-72]
	_ = x[EventTabNew-73]
	_ = x[EventTabClosed-74]
	_ = x[EventWinEnter-75]
	_ = x[EventWinLeave-76]
	_ = x[EventTabEnter-77]
	_ = x[EventTabLeave-78]
	_ = x[EventCmdwinEnter-79]
	_ = x[EventCmdwinLeave-80]
	_ = x[EventCmdlineChanged-81]
	_ = x[EventCmdlineEnter-82]
	_ = x[EventCmdlineLeave-83]
	_ = x[EventInsertEnter-84]
	_ = x[EventInsertChange-85]
	_ = x[EventInsertLeave-86]
	_ = x[EventInsertCharPre-87]
	_ = x[EventTextChanged-88]
	_ = x[EventTextChangedI-89]
	_ = x[EventTextChangedP-90]
	_ = x[EventTextYankPost-91]
	_ = x[EventColorSchemePre-92]
	_ = x[EventColorScheme-93]
	_ = x[EventRemoteReply-94]
	_ = x[EventQuickFixCmdPre-95]
	_ = x[EventQuickFixCmdPost-96]
	_ = x[EventSessionLoadPost-97]
	_ = x[EventMenuPopup-98]
	_ = x[EventCompleteDone-99]
	_ = x[EventUser-100]
}

const _Event_name = "BufNewFileBufReadPreBufReadBufReadPostBufReadCmdFileReadPreFileReadPostFileReadCmdFilterReadPreFilterReadPostStdinReadPreStdinReadPostBufWriteBufWritePreBufWritePostBufWriteCmdFileWritePreFileWritePostFileWriteCmdFileAppendPreFileAppendPostFileAppendCmdFilterWritePreFilterWritePostBufAddBufCreateBufDeleteBufWipeoutTerminalOpenBufFilePreBufFilePostBufEnterBufLeaveBufWinEnterBufWinLeaveBufUnloadBufHiddenBufNewSwapExistsFileTypeSyntaxEncodingChangedTermChangedOptionSetVimEnterGUIEnterGUIFailedTermResponseQuitPreExitPreVimLeavePreVimLeaveFileChangedShellFileChangedShellPostFileChangedRODiffUpdatedDirChangedShellCmdPostShellFilterPostCmdUndefinedFuncUndefinedSpellFileMissingSourcePreSourcePostSourceCmdVimResizedFocusGainedFocusLostCursorHoldCursorHoldICursorMovedCursorMovedIWinNewTabNewTabClosedWinEnterWinLeaveTabEnterTabLeaveCmdwinEnterCmdwinLeaveCmdlineChangedCmdlineEnterCmdlineLeaveInsertEnterInsertChangeInsertLeaveInsertCharPreTextChangedTextChangedITextChangedPTextYankPostColorSchemePreColorSchemeRemoteReplyQuickFixCmdPreQuickFixCmdPostSessionLoadPostMenuPopupCompleteDoneUser"

var _Event_index = [...]uint16{0, 10, 20, 27, 38, 48, 59, 71, 82, 95, 109, 121, 134, 142, 153, 165, 176, 188, 201, 213, 226, 240, 253, 267, 282, 288, 297, 306, 316, 328, 338, 349, 357, 365, 376, 387, 396, 405, 411, 421, 429, 435, 450, 461, 470, 478, 486, 495, 507, 514, 521, 532, 540, 556, 576, 589, 600, 610, 622, 637, 649, 662, 678, 687, 697, 706, 716, 727, 736, 746, 757, 768, 780, 786, 792, 801, 809, 817, 825, 833, 844, 855, 869, 881, 893, 904, 916, 927, 940, 951, 963, 975, 987, 1001, 1012, 1023, 1037, 1052, 1067, 1076, 1088, 1092}

func (i Event) String() string {
	if i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NArgs0-0]
	_ = x[NArgs1-1]
	_ = x[NArgsZeroOrMore-2]
	_ = x[NArgsZeroOrOne-3]
	_ = x[NArgsOneOrMore-4]
}

const _NArgs_name = "-nargs=0-nargs=1-nargs=*-nargs=?-nargs=+"

var _NArgs_index = [...]uint8{0, 8, 16, 24, 32, 40}

func (i NArgs) String() string {
	if i >= NArgs(len(_NArgs_index)-1) {
		return "NArgs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NArgs_name[_NArgs_index[i]:_NArgs_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlavorVim-0]
	_ = x[FlavorGvim-1]
}

const _Flavor_name = "vimgvim"

var _Flavor_index = [...]uint8{0, 3, 7}

func (i Flavor) String() string {
	if i >= Flavor(len(_Flavor_index)-1) {
		return "Flavor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Flavor_name[_Flavor_index[i]:_Flavor_index[i+1]]
}
