# Code generated by genconfig. DO NOT EDIT.
export GO_VERSIONS="go1.16.8 go1.17.1"
export VIM_VERSIONS="v8.1.1711 v8.1.2056 v8.2.3450"
export GVIM_VERSIONS="v8.1.1711 v8.1.2056 v8.2.3450"

export MAX_GO_VERSION=go1.17.1
export MAX_VIM_VERSION=v8.2.3450
export MAX_GVIM_VERSION=v8.2.3450

export DEFAULT_VIM_COMMAND="vim"
export DEFAULT_GVIM_COMMAND="xvfb-run -a gvim -f"

export VALID_FLAVORS="vim gvim"
