# Code generated by genconfig. DO NOT EDIT.
export GO_VERSIONS="go1.12.9 go1.13"
export VIM_VERSIONS="v8.1.1158 v8.1.1657 v8.1.1711"
export GVIM_VERSIONS="v8.1.1158 v8.1.1657 v8.1.1711"
export NEOVIM_VERSIONS="v0.3.5"

export MAX_GO_VERSION=go1.13
export MAX_VIM_VERSION=v8.1.1711
export MAX_GVIM_VERSION=v8.1.1711
export MAX_NEOVIM_VERSION=v0.3.5

export DEFAULT_VIM_COMMAND="vim"
export DEFAULT_GVIM_COMMAND="xvfb-run -a gvim -f"
export DEFAULT_NEOVIM_COMMAND="nvim"

export VALID_FLAVORS="vim gvim neovim"
